# PRACTICE SET
name = "muhammadowais"
print(name[3])
print(name[0:3])
print(name[1:4])
print(name[:4])
print(name[0:])
print(len(name))
print(name.strip())
print(name.upper())
print(name.lower())
print(name.find("o"))
print(name.replace("owais","amjad"))
print(name.find("o"))
print(name.count("o"))
print(name.join(["muhammadowais","amjad"]))
fathername = "muhammadamjad"
print(len(fathername))
print(fathername.lower())
print(fathername.upper())
print(fathername.strip())
print(fathername.replace("amjad","owais"))
print(fathername.find("a"))
print(fathername.count("a"))
print(fathername.startswith("a"))
print(fathername.endswith("a"))
listbnai = [1,2,"abs",33.3]
listbnai[0]="orange"
listbnai.append("x")
listbnai.remove("x")
listbnai.clear()
# listbnai.sort()
listbnai.insert(0,"ali")
print(listbnai)
my_tupel = (1,2,"abcs",33.2)
